KodLandSite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.main, name='main'),
    path('add', views.add, name='add'),
    path('<int:article_id>/', views.detail, name='detail'),
]

app/models.py
from django.db import models
import datetime

# Create your models here.
class Article(models.Model):
    title = models.CharField('Название статьи', max_length=200)
    img = models.ImageField('Картинка', upload_to='img')
    description = models.CharField('Краткое описание', max_length=1000)
    text = models.TextField('Текст статьи', null=True)
    date = models.DateTimeField('Дата и время публикации', null=True, blank=True)

    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import render
from .models import Article
from django.http import Http404

# Create your views here.
def main(request):
    info=Article.objects.all()
    latest_articles=Article.objects.order_by('-date')[:1]

    return render(request, 'html/main.html', context={'info':info, 'latest_articles':latest_articles})

def add(request):
    return render(request, 'html/add.html')

def detail(request, article_id):
    try:
        a= Article.objects.get( id = article_id)
    except:
        raise http404("Статья не найдена")

    return render(request, 'html/article.html', context={'article':a})

app/templates/html/add.html
{% extends "index.html" %}

{% block content %}
{% load static %}
<main>
  <div class="Add">
    <div class="container">
      <h1>Добавить статью</h1>
      <form action="index.html" method="post">
        <div class="row">
          <p><input type="text" placeholder="Введите название статьи"></p>
          <button type="sumbit" name="button">
            <p>Опубликовать</p>
          </button>
        </div>
        <div class="row">
          <textarea name="name" rows="8" cols="80"></textarea>
          <div class="border">
            <h3>Загрузить Изобрание</h3>
            <input class="image" type="image">
          </div>
        </div>
      </form>
    </div>
</main>
{% endblock %}

app/templates/html/article.html
{% extends "index.html" %}

{% block content %}
{% load static %}
  <main>
    <div class="Description__container">
      <h1>{{ article.title }}</h1>
      <img src="{{ article.img.url }}">
      <p>{{ article.text }}</p>
    </div>
  </main>
<script src="{% static "js/js.js" %}"></script>
{% endblock %}

app/templates/html/main.html
{% extends "index.html" %}

{% block content %}
{% load static %}
<main>
  <div class="New">
    {% for all in latest_articles %}
      <div class="container">
        <div class="row-between">
          <section>
            <h3>NEW</h3>
            <h1>{{ all.title }}</h1>
            <p>{{ all.description }}</p>
            <div class="read">
              <a class="read__btn" href="{% url 'app:detail' all.id %}">
                <p>Читать</p>
              </a>
            </div>
          </section>
          <img src="{{ all.img.url }}">
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="Articles">
    <div class="container">
      <h3>Другие статьи</h3>
      <div class="row">
        {% for all in info %}
          <a class="show__article" href="{% url 'app:detail' all.id %}">
            <div class="article">
              <p>{{ all.date }} {{ all.time }}</p>
              <img src="{{ all.img.url }}">
              <h3>{{ all.title }}</h3>
            </div>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
</main>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
    <title>New Tab</title>
    <script src="{% static "js/jquery-3.5.1.min.js" %}"></script>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="row-between">
          <div class="row">
            <a class="logo" href="{% url 'app:main' %}">
              <img src="{% static 'icons/Logo_Kodland.svg' %}">
            </a>
            <p class="text">Блог</p>
          </div>
          <a class="add" href="{% url 'app:add' %}">
            <p>+ Добавить статью</p>
          </a>
        </div>
      </div>
    </header>
    {% block content %}{% endblock %}
  </body>
</html>